// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AllCheckboxesController from "./all_checkboxes_controller"
application.register("all-checkboxes", AllCheckboxesController)

import AutofocusController from "./autofocus_controller"
application.register("autofocus", AutofocusController)

import AutogramController from "./autogram_controller"
application.register("autogram", AutogramController)

import NewAutogramController from "./new_autogram_controller"
application.register("new-autogram", NewAutogramController)

import DebounceController from "./debounce_controller"
application.register("debounce", DebounceController)

import DismissibleAlertController from "./dismissible_alert_controller"
application.register("dismissible-alert", DismissibleAlertController)

import FormController from "./form_controller"
application.register("form", FormController)

import MessageDraftsController from "./message_drafts_controller"
application.register("message-drafts", MessageDraftsController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import DropzoneController from "./dropzone_controller"
application.register("dropzone", DropzoneController)

import TriStateCheckboxController from "./tri_state_checkbox_controller"
application.register("tri-state-checkbox", TriStateCheckboxController)

import TurboContentController from "./turbo_content_controller"
application.register("turbo-content", TurboContentController)

import ContentWithSeparator from "./content_with_separator"
application.register("content-with-separator", ContentWithSeparator)

import VisitedLinks from "./visited_links_controller"
application.register("visited-links", VisitedLinks)
