timeout: 120
service:
  externalPort: 5000
  internalPort: 5000
image:
  secrets:
  - name: skdigital-bonet-registry
application.migrateCommand: ["bin/rails", "db:migrate"]
ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 256m
livenessProbe:
  initialDelaySeconds: 5
  timeoutSeconds: 5
  probeType: "httpGet"
  path: "/health"
readinessProbe:
  initialDelaySeconds: 5
  timeoutSeconds: 10
  probeType: "httpGet"
  path: "/health"
resources:
  requests:
    memory: 700Mi
  limits:
    memory: 1Gi
persistence:
  enabled: true
  volumes:
  - name: govbox-pro-storage
    mount:
      path: /rails/storage
    claim:
      accessMode: ReadWriteMany
      size: 10Gi
      storageClass: nfs-client
workers:
  worker:
    replicaCount: "1"
    command: ["bundle", "exec", "good_job", "start", "--probe-port=5000"]
    startupProbe:
      probeType: "httpGet"
      path: "/status/started"
    livenessProbe:
      probeType: "httpGet"
      path: "/status/connected"
    readinessProbe:
      probeType: "httpGet"
      path: "/status/started"
    resources:
      requests:
        memory: 3Gi
      limits:
        memory: 3Gi
