default: &default
  adapter: postgresql
  encoding: unicode
  pool: 50
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: govbox_pro_development

test:
  <<: *default
  database: govbox_pro_test

staging:
  url: <%= ENV['DATABASE_URL'] %>
  pool: 30

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: 50
